// <auto-generated />
namespace Weathers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSerifType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSerifType));
        
        string IMigrationMetadata.Id
        {
            get { return "201612230929333_AddSerifType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
